export enum RequestEndpoint {
	// GROUPS
	POST_ADD_GROUP,
	GET_GROUP_BY_ID,
	GET_USER_GROUPS,
	GET_ALL_GROUPS,
	PUT_ADD_RIDE_TO_GROUP,
	PUT_ADD_USER_TO_GROUP,
	PUT_ADD_LOCATION_TO_GROUP,
	DELETE_GROUP_BY_ID,
	// INVITES
	GET_INVITES_BY_USER_ID,
	GET_ALL_INVITES,
	POST_INVITE,
	GET_INVITE_BY_ID,
	PUT_CHANGE_INVITE,
	DELETE_INVITE_BY_ID,
}
