export enum RequestEndpoint {
  //Grups
  POST_ADD_GROUP,
  GET_GROUP_BY_ID,
  GET_USER_GROUPS,
  GET_ALL_GROUPS,
  PUT_ADD_RIDE_TO_GROUP,
  PUT_ADD_USER_TO_GROUP,
  PUT_ADD_LOCATION_TO_GROUP,
  DELETE_GROUP_BY_ID,
}
